blog_matt/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
	resources :posts do
		resources :comments
	end
	
	root "posts#index"

	get '/about', to: 'pages#about'
end

blog_matt/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog_matt/app/models/comment.rb
class Comment < ApplicationRecord
  	belongs_to :post
end

blog_matt/app/models/post.rb
class Post < ApplicationRecord
	acts_as_paranoid
	has_many :comments, dependent: :destroy
	belongs_to :user

	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true

	accepts_nested_attributes_for :comments

	def user
		User.with_deleted.find(user_id)
	end

	has_attached_file :image, styles: { large: "600x600>", 
										medium: "300x300>", 
										small: "150x150#", 
										thumb: "100x100#" }, 
										default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

blog_matt/app/models/user.rb
class User < ApplicationRecord
	acts_as_paranoid
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable

	has_many :posts
end

blog_matt/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  		devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

blog_matt/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comments = @post.comments.create(params[:comment].permit(:name, :body))
		@comments.save

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end
end

blog_matt/app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
		
	end
end

blog_matt/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	
	def index
		if request.format == "xls"	
			@posts = Post.all.order('created_at desc').paginate(page: params[:page])
		else
			@posts = Post.all.order('created_at desc').paginate(page: params[:page], per_page: 5)
		end

		respond_to do |format|
		   	format.html
		    format.xls 
		end
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)
		
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body, :image))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to root_path
	end

	private
		def post_params
			params.require(:post).permit(:title, :body, :image)
		end

end

blog_matt/app/helpers/application_helper.rb
module ApplicationHelper
end

blog_matt/app/helpers/comments_helper.rb
module CommentsHelper
end

blog_matt/app/helpers/pages_helper.rb
module PagesHelper
end

blog_matt/app/helpers/posts_helper.rb
module PostsHelper
end

blog_matt/app/views/comments/_comment.html.erb
<div class="comment clearfix">

	<div class="comment_content">

		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
		
	</div>
		<% if user_signed_in? %>
		<p><%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button", data: { confirm: 'Delete this comment?' } %>
		</p>
	<% end %>
</div>

blog_matt/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>
	<br>
	<p>
		<%= f.submit %>
	</p>
<% end %>

blog_matt/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matthaeus Marinho</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="sidebar">
    	<div id="logo">
    		<%= link_to root_path do %>
    			<%= image_tag "perfil2.jpg" %>
    		<% end %>	
    	</div>
      
      <div id="title">
        <b>Matthaeus Marinho</b>
      </div>

    	<ul>
    		<li class="category">Blog</li>
    		<li><%= link_to "Home", root_path %></li>
    		<li><%= link_to "About", about_path %></li>
    	</ul>
    	<ul>
      	<li class="category">Social</li>
    		<li><a href="https://www.facebook.com/matthaeus.marinho">Facebook</a></li>
    		<li><a href="mailto:mbm2@cin.ufpe.br">Email</a></li>
    	</ul>
      <ul>
        <li class="category">Download</li>
        <li><%= link_to "Excel", posts_path(format: "xls") %></li>
      </ul>

      <% if user_signed_in? %>
        <p class="sign_in"><%= current_user.name %></p>
      <% end %>

    </div>

    <div id="main_content">
      <div id="header">
        <% if current_page?(root_path) or current_page?(posts_path) %>
          <p>All Posts</p>
        <% elsif current_page?(about_path) %>
          <p>About</p>
        <% else %>
          <%= link_to "Back to All Posts", root_path %>
        <% end %>

        <% if user_signed_in? %>
          <div class="buttons">
            <%= link_to "New Post", new_post_path, class: 'button' %>
            <%= link_to "Edit Profile", edit_user_registration_path, class: 'button' %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'button' %>
          </div>
        <% else %>
          <div class="buttons">
            <%= link_to "Sign Up", new_user_registration_path, class: 'button' %>
            <%= link_to "Login", new_user_session_path, class: 'button' %>
          </div>
        <% end %>

        <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert") %>
        <% end %>

      </div>

      <%= yield %>
      
    </div>

  </body>
</html>

blog_matt/app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "perfil.jpeg" %>
	</div>

	<div id="content">
		<h1>Matthaeus Bezerra Marinho</h1>
		<p>Bem vindo meu blog! Criado para o processo seletivo da <strong>Tracking Trade</strong>.</p>
		<p>Projeto: Aplicação em <strong>Ruby on Rails</strong> de um blog. O blog deverá conter o nome do estagiario na tela de início, por ex: 'blog do George'.</p>
		<p>1 - fazer uma aplicação de blog com todo sistema de <strong>CRUD</strong>.</p>
		<p>2 - a listagem do blog deverá ser por data da postagem.</p>
		<p>3 - fazer um <strong>Nested</strong> com comentários, cada postagem podera ter comentários dentro dele.</p>
		<p>4 - implementacao do <strong>Devise</strong>, deverá ter usuário admin (pode postar e comentar, excluir, editar os posts) e o usuario comum que só poderá comentar.</p>
		<p>5 - implementar o <strong>Paperclip</strong>, as postagens agora terão imagens junto com a postagem. Detalhe: a imagem deverá aparecer junto com o post em formato thumb.</p>
		<p>6	- implementar a <strong>gem Paranoia</strong>.</p>
		<p>7	- implementar download de <strong>Excel</strong> das postagens.</p>
	</div>
</div>

blog_matt/app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
		</div>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>
	<p>
		<%= f.label :image %><br>
		<%= f.file_field :image %>
	</p>

	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

blog_matt/app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Post</h1>

	<%= render 'form' %>
</div>

blog_matt/app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<% if post.image.file? %>
			<td><%= image_tag post.image.url(:thumb) %></td>
		<% end %>
		<h2 class="title"><%= link_to post.title, post %></h2>
		<%= post.user.name %>
		| <%= post.created_at.strftime("%d de %B de %Y") %>
	</div>
<% end %>

<div class="post_wrapper">
	<%= will_paginate @posts, previous_label: "Older", next_label: "Newer", inner_window: 1, outer_window: 0 %>
</div>

blog_matt/app/views/posts/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Title</Data></Cell>
        <Cell><Data ss:Type="String">User</Data></Cell>
        <Cell><Data ss:Type="String">Date</Data></Cell>
        <Cell><Data ss:Type="String">Body</Data></Cell>
      </Row>
    <% @posts.each do |post| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= post.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= post.title %></Data></Cell>
        <Cell><Data ss:Type="String"><%= post.user.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= post.created_at %></Data></Cell>
        <Cell><Data ss:Type="Text"><%= post.body %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

blog_matt/app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>New Post</h1>

	<%= render 'form' %>
</div>

blog_matt/app/views/posts/show.html.erb
<div id="post_content">
	<h1 class="title">
		<%= @post.title %>
	</h1>

	<p class="date">
		Posted <%= time_ago_in_words(@post.created_at) %> Ago

		<% if @post.user == current_user %>
			| <%= link_to 'Edit', edit_post_path(@post) %>
			| <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Delete this post?' } %>
		<% end %>
	</p>

	<% if @post.image.file? %>
		<%= image_tag @post.image.url(:large) %>
	<% end %>

	<p class="body">
		<%= @post.body %>
	</p>

	<div id="comments">
		<h2><%= @post.comments.count %> Comments</h2>
		<%= render @post.comments %>

		<h3>Add a comment</h3>
		<%= render "comments/form" %>
	</div>
</div>